import platform
from datetime import datetime
from pathlib import Path

from pcrisk.core.paths import AUDIT_DIR
from pcrisk.automations.credit_worksheet.engine import compute_field_metrics
from pcrisk.automations.credit_worksheet.fields import FieldResult

def write_audit_report(
    user: str,
    original_filename: str,
    output_path: Path,
    template_name: str,
    field_results: list[FieldResult],
    readability_info: dict,
) -> tuple[Path, dict]:
    AUDIT_DIR.mkdir(parents=True, exist_ok=True)

    metrics = compute_field_metrics(field_results)

    audit_path = AUDIT_DIR / f"{output_path.stem}_audit.txt"
    counter = 2
    while audit_path.exists():
        audit_path = AUDIT_DIR / f"{output_path.stem}_audit_{counter}.txt"
        counter += 1

    lines = [
        "PHILLIPCAPITAL RISK MANAGEMENT - CREDIT WORKSHEET AUDIT",
        "=" * 60,
        f"Source PDF:        {original_filename}",
        f"Template Used:     {template_name}",
        f"Generated Output:  {output_path.name}",
        f"Fields Found:      {metrics['fields_found_label']}",
        f"Ready Fields:      {metrics['ready']}",
        f"Valid Blanks:      {metrics['valid_blanks']}",
        f"Needs Review:      {metrics['needs_review']}",
        f"Missing Fields:    {metrics['missing']}",
        f"PDF Readability:   {readability_info.get('readability', '')}",
        f"Generated By:      {user}",
        f"Machine:           {platform.node()}",
        f"Timestamp:         {datetime.now().strftime('%Y-%m-%d %I:%M:%S %p')}",
        "",
        "FIELD-LEVEL DETAIL",
        "-" * 60,
    ]

    for r in field_results:
        value = r.display_value if r.display_value else "(blank)"
        lines.append(
            f"{r.excel_cell:<5} | code {r.expression:<10} | {r.status:<12} | {value:<18} | {r.label}"
        )

    audit_path.write_text("\n".join(lines), encoding="utf-8")
    return audit_path, metrics
